management:
  endpoint:
    health:
      enabled: true
      show-details: always
  endpoints:
    web:
      exposure:
        include: health,loggers,readiness111
#spring:
#  security:
#    user:
#      name: myuser
#      password: mypassword
